//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.22 at 02:59:56 AM GMT+06:00 
//


package com.geekbrains.spring.web.soap.products;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productXML" type="{http://www.geekbrains.com/spring/web/soap/products/productXML}productXML"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productXML"
})
@XmlRootElement(name = "getProductByIdResponse")
public class GetProductByIdResponse {

    @XmlElement(required = true)
    protected ProductXML productXML;

    /**
     * Gets the value of the productXML property.
     * 
     * @return
     *     possible object is
     *     {@link ProductXML }
     *     
     */
    public ProductXML getProductXML() {
        return productXML;
    }

    /**
     * Sets the value of the productXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductXML }
     *     
     */
    public void setProductXML(ProductXML value) {
        this.productXML = value;
    }

}
