server:
  port: 8185
  servlet:
    context-path: /web-market-statistic
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./stat;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

